
import com.sun.javafx.geom.Vec2d;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class Candidato extends javax.swing.JFrame {

  String votos[][];

  public Candidato() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setText("Iniciar conteo");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Ganador");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jButton3.setText("votos por candidatos");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton4.setText("votos en blanco");

    jButton5.setText("votos anulados");

    jButton6.setText("mesa menos votada");

    jButton7.setText("mesa mas votada");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton1)
          .addComponent(jButton2)
          .addComponent(jButton3)
          .addComponent(jButton4))
        .addGap(108, 108, 108)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton5)
          .addComponent(jButton6)
          .addComponent(jButton7))
        .addContainerGap(74, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(70, 70, 70)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jButton5))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(jButton2))
          .addGroup(layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(jButton6)))
        .addGap(34, 34, 34)
        .addComponent(jButton3)
        .addGap(3, 3, 3)
        .addComponent(jButton7)
        .addGap(28, 28, 28)
        .addComponent(jButton4)
        .addContainerGap(82, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int numCandidatos = Integer.parseInt(JOptionPane.showInputDialog(null, "ingres numers de candidatos"));
    int mesas = Integer.parseInt(JOptionPane.showInputDialog(null, "ingres numers de mesas"));
    numCandidatos++;
    mesas++;
    votos = new String[numCandidatos][mesas];
    agregarCandidato();
    agregarMesa();
    agregarVotos();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    int may = 0, may2 = 0;
    int fila = 0, col = 0;
//    boolean entre = true;
//    for (int x = 0; x < votos.length; x++) {
//      System.out.print("|");
//      for (int y = 0; y < votos[x].length; y++) {
//        if(x==0 && y==0){
//          System.out.print("  ");
//        }else{
//           System.out.print(votos[x][y] + " ");
//        }
//
//      }
//      System.out.println("|");
//    }
    int c = 0;
    for (int i = 1; i < votos[0].length; i++) {
      may = 0;
      for (int j = 1; j < votos.length; j++) {
        may += Integer.parseInt(votos[j][i]);
      }
      if (may > may2) {
        may2 = may;
      }
    }
    System.out.println(may2);
    int index = bus(may2);
    System.out.println(index);
    //perdeodres
    String perd = "";
      for (int j = 1; j < votos.length; j++) {
        if(j!=index)perd+=votos[j][0]+" ";
      }
    
    JOptionPane.showMessageDialog(rootPane, "el ganador es " + votos[index][0]+"\n"+"perdedores "+perd);

  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

  }//GEN-LAST:event_jButton3ActionPerformed

  public int bus(int cad) {
    int c = 0, a =0;
    for (int i = 1; i < votos[0].length; i++) {
      c=0;
      for (int j = 1; j < votos.length; j++) {
        c+=Integer.parseInt(votos[j][i]);
        if(j==1)a++;
      }
      
      if(cad == c){
        return a;
      }
    }
    return -1;
  }

  public void agregarCandidato() {
    for (int i = 1; i < votos.length; i++) {
      votos[i][0] = JOptionPane.showInputDialog(null, "ingrese candidato no" + i);
    }
  }

  public void agregarMesa() {
    for (int i = 1; i < votos[0].length; i++) {
      votos[0][i] = "mesa " + i;
    }
  }

  public void agregarVotos() {
    for (int i = 1; i < votos[0].length; i++) {
      for (int j = 1; j < votos.length; j++) {
        votos[j][i] = JOptionPane.showInputDialog(null, "ingrese voto de la mesa " + j);
      }
    }
  }

  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Candidato().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  // End of variables declaration//GEN-END:variables
}
