
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class Elecciones extends javax.swing.JFrame {

  String mesas[];
  String candidatos[];
  int votos[][];

  public Elecciones() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton1.setText("Iniciar Conteo");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Ganador");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jButton3.setText("Votos por candidato");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton4.setText("Votos en blanco");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jButton5.setText("Votos anulados");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });

    jButton6.setText("Mesas menos votada");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton6ActionPerformed(evt);
      }
    });

    jButton7.setText("Mesa mas votada");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton7ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(53, 53, 53)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(73, 73, 73))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(55, 55, 55)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jButton5)
            .addGap(50, 50, 50)
            .addComponent(jButton6)
            .addGap(54, 54, 54)
            .addComponent(jButton7)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jButton1)
            .addGap(50, 50, 50)
            .addComponent(jButton2)
            .addGap(54, 54, 54)
            .addComponent(jButton3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
            .addComponent(jButton4)
            .addGap(50, 50, 50))))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    int numCandidatos = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese cantidad de candidatos"));
    int numMesas = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese numeros de mesas"));
    numCandidatos += 2;
    candidatos = new String[numCandidatos];
    mesas = new String[numMesas];
    votos = new int[numCandidatos][numMesas];
    agregarCandidatos();
    agregarMesas();
    agregarVotos();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    int may = 0;
    int s;
    int posGan = 0, c = -1;
    for (int i = 0; i < votos.length - 2; i++) {
      s = 0;
      for (int j = 0; j < votos[0].length; j++) {
        s += votos[i][j];
        if (j == 0) {
          c++;
        }
      }
      if (s > may) {
        may = s;
        posGan = c;
      }
    }

    String perdedores = "";
    for (int i = 0; i < votos.length - 2; i++) {
      if (i != posGan) {
        perdedores += candidatos[i] + "\n";
      }
    }
    JOptionPane.showMessageDialog(rootPane, "GANADOR\n" + candidatos[posGan] + "\n PERDODORES\n" + perdedores);
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    String informacion = "";
    int s;
    for (int i = 0; i < votos.length - 2; i++) {
      s = 0;
      for (int j = 0; j < votos[0].length; j++) {
        s += votos[i][j];
      }
      informacion += candidatos[i] + ":      " + s + "\n";
    }

    JOptionPane.showMessageDialog(rootPane, informacion);

  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    int men, s, posMen = 0, aux1 = 0;

    men = 0;
    for (int j = 0; j < votos.length; j++) {
      men += votos[j][0];
    }
    for (int i = 0; i < votos[0].length; i++) {
      s = 0;
      for (int j = 0; j < votos.length; j++) {
        s += votos[j][i];
      }
      if (men < s) {
        continue;
      } else {
        posMen = i;
        men = s;
      }
    }
    System.out.println(men + " " + aux1);
    JOptionPane.showMessageDialog(rootPane, "la mesa menos votada fue " + mesas[posMen] + " con " + men);

  }//GEN-LAST:event_jButton6ActionPerformed

  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    int men = 0, s, posMen = 0;
    for (int i = 0; i < votos[0].length; i++) {
      s = 0;
      for (int j = 0; j < votos.length; j++) {
        s += votos[j][i];
      }
      if (s > men) {
        men = s;
        posMen = i;
      }
    }
    JOptionPane.showMessageDialog(rootPane, "la mesa mas votada fue " + mesas[posMen] + " con " + men);

  }//GEN-LAST:event_jButton7ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    String mensaje = "VOTOS EN BLANCO\n";
    int s = 0;

    for (int i = 0; i < votos[0].length; i++) {
      s += votos[candidatos.length - 2][i];
    }
    for (int i = 0; i < votos[0].length; i++) {
      mensaje += mesas[i] + ":        " + votos[candidatos.length - 2][i] + "\n";
    }
    JOptionPane.showMessageDialog(rootPane, mensaje + "\n\n" + "votos en blanco en total: " + s);
  }//GEN-LAST:event_jButton4ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    String mensaje = "VOTOS ANULADOS\n";
    int s = 0;

    for (int i = 0; i < votos[0].length; i++) {
      s += votos[candidatos.length - 1][i];
    }
    for (int i = 0; i < votos[0].length; i++) {
      mensaje += mesas[i] + ":        " + votos[candidatos.length - 1][i] + "\n";
    }
    JOptionPane.showMessageDialog(rootPane, mensaje + "\n\n" + "votos anulados en total: " + s);


  }//GEN-LAST:event_jButton5ActionPerformed

  public void agregarCandidatos() {
    for (int i = 0; i < candidatos.length - 2; i++) {
      candidatos[i] = JOptionPane.showInputDialog(null, "ingrese nombre del candidato " + (i + 1));
    }
    candidatos[candidatos.length - 2] = "votos en blanco";
    candidatos[candidatos.length - 1] = "votos anulados";
  }

  public void agregarMesas() {
    for (int i = 0; i < mesas.length; i++) {
      mesas[i] = "mesa " + (i + 1);
    }
  }

  public void agregarVotos() {
    for (int i = 0; i < votos[0].length; i++) {
      for (int j = 0; j < votos.length - 2; j++) {
        votos[j][i] = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese votos de la " + mesas[i] + " del candidato " + candidatos[j]));
      }
      for (int j = votos.length - 2; j < votos.length; j++) {
        votos[j][i] = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese " + candidatos[j] + " del candidato " + mesas[i]));
      }
    }

  }

  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Elecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Elecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Elecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Elecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Elecciones().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  // End of variables declaration//GEN-END:variables
}
