
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class Menu extends javax.swing.JFrame {

  DefaultTableModel modelo;
  Empleado empleado[];
  Empleado emp;
  int index, num;

  public Menu() {
    initComponents();
    modelo = new DefaultTableModel();
    modelo.addColumn("nombre");
    modelo.addColumn("documwento");
    modelo.addColumn("genero");
    modelo.addColumn("tiene hijos");
    modelo.addColumn("precio");
    this.tabla.setModel(modelo);

    this.index = 0;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Grupo1 = new javax.swing.ButtonGroup();
    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    nombre = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    documento = new javax.swing.JTextField();
    genero = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    sueldo = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    opcSi = new javax.swing.JRadioButton();
    opcNo = new javax.swing.JRadioButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    tabla = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("Empleado");

    jButton1.setText("numeros de empleados");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("guardar empleado");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        guardar(evt);
      }
    });

    jButton3.setText("Consultar ekmpleado");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton4.setText("buscar empleado");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jButton5.setText("Actualizar empleado");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });

    jLabel2.setText("Nombre");

    jLabel3.setText("Documento");

    genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", " Femenino" }));
    genero.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        generoActionPerformed(evt);
      }
    });

    jLabel4.setText("Genero");

    jLabel5.setText("Sueldo");

    jLabel6.setText("Tienes hijos?");

    Grupo1.add(opcSi);
    opcSi.setText("si");
    opcSi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        opcSiActionPerformed(evt);
      }
    });

    Grupo1.add(opcNo);
    opcNo.setText("no");

    tabla.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "nombre", "documento", "genero", "tiene hijos", "sueldo"
      }
    ));
    jScrollPane2.setViewportView(tabla);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jLabel4))
          .addGroup(layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5)
              .addComponent(jLabel6)
              .addComponent(jLabel2)
              .addComponent(jLabel3))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(documento)
                  .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(opcSi)
                .addGap(18, 18, 18)
                .addComponent(opcNo))))
          .addGroup(layout.createSequentialGroup()
            .addGap(70, 70, 70)
            .addComponent(jLabel1)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(29, 29, 29))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {documento, nombre, sueldo});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(55, 55, 55)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jButton1)
            .addGap(18, 18, 18)
            .addComponent(jButton2)
            .addGap(26, 26, 26)
            .addComponent(jButton3)
            .addGap(18, 18, 18)
            .addComponent(jButton4)
            .addGap(30, 30, 30)
            .addComponent(jButton5))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)
                    .addComponent(sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(228, 228, 228)))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(opcSi)
              .addComponent(opcNo))
            .addGap(28, 28, 28)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(242, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void opcSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSiActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_opcSiActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    this.num = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese cantidad de empleados"));
    empleado = new Empleado[num];
  }//GEN-LAST:event_jButton1ActionPerformed

  private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
    if (this.index < this.num) {
      String nombre = this.nombre.getText();
      String documento = this.documento.getText();
      double salario = Double.valueOf(sueldo.getText());
      String genero = this.genero.getSelectedItem().toString();
      boolean tieneHijos = false;
      if (opcSi.isSelected()) {
        tieneHijos = true;
      } else if (opcNo.isSelected()) {
        tieneHijos = false;
      }
      empleado[this.index] = new Empleado(nombre, documento, genero, tieneHijos, salario);
      this.nombre.setText("");
      this.documento.setText("");
      sueldo.setText("");
      Grupo1.clearSelection();
      String a[] = empleado[this.index].toString().split("\\|");
      modelo.addRow(a);
    } else {
      System.out.println("no se peuede");
    }
    this.index++;


  }//GEN-LAST:event_guardar

  public void agregar(int buscarCc) {
    String nombre = JOptionPane.showInputDialog(null, "ingrese nombre");
    String documento = JOptionPane.showInputDialog(null, "ingrese docuemnto");
    double salario = Double.valueOf(JOptionPane.showInputDialog(null, "ingrese salario"));
    String genero = JOptionPane.showInputDialog(null, "ingrese genero");
    boolean tieneHijos = true;

    empleado[buscarCc].setNombre(nombre);
    empleado[buscarCc].setDocuemnto(documento);
    empleado[buscarCc].setTieneHijos(tieneHijos);
    empleado[buscarCc].setSueldo(salario);
    empleado[buscarCc].setGenero(genero);
  }
  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    if (empleado.length > 0) {
      String cc = JOptionPane.showInputDialog(rootPane, "ingrese documento a buscar");
      int buscarCc = buscar(cc);
      if (buscarCc >= 0) {
        agregar(buscarCc);
      } else {
        JOptionPane.showConfirmDialog(rootPane, "no se encontro el empleado buscado");
      }
    }
    int fila = tabla.getRowCount();
    for (int i = fila - 1; i >= 0; i--) {
      modelo.removeRow(i);
    }
    for (Empleado empleado1 : empleado) {
      String a[] = empleado1.toString().split("\\|");
      modelo.addRow(a);
    }
  }//GEN-LAST:event_jButton5ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    if (empleado.length > 0) {
      String cc = JOptionPane.showInputDialog(rootPane, "ingrese documento a buscar");
      int buscarCc = buscar(cc);
      if (buscarCc >= 0) {
        JOptionPane.showConfirmDialog(rootPane, "El empleado " + cc + " se encuentra en la posicion " + buscarCc);
      } else {
        JOptionPane.showConfirmDialog(rootPane, "no se encontro el empleado buscado");
      }
    }


  }//GEN-LAST:event_jButton4ActionPerformed

  private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_generoActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String cad = "";
    if (empleado.length > 0) {
      String cc = JOptionPane.showInputDialog(rootPane, "ingrese documento a buscar");
      int buscarCc = buscar(cc);
      if (buscarCc >= 0) {
        String a[] = empleado[buscarCc].toString().split("\\|");
        for (String s : a) {
          cad += s + "\n";
        }
        JOptionPane.showConfirmDialog(rootPane, cad);
      } else {
        JOptionPane.showConfirmDialog(rootPane, "no se encontro el empleado buscado");
      }
    }

  }//GEN-LAST:event_jButton3ActionPerformed

  public int buscar(String cad) {
    int a = 0;
    for (Empleado empleado1 : empleado) {
      if (empleado1 != null) {
        if (empleado1.getDocuemnto().equals(cad)) {
          return a;
        }
      }

      a++;
    }
    return -1;
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Menu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup Grupo1;
  private javax.swing.JTextField documento;
  private javax.swing.JComboBox<String> genero;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTextField nombre;
  private javax.swing.JRadioButton opcNo;
  private javax.swing.JRadioButton opcSi;
  private javax.swing.JTextField sueldo;
  private javax.swing.JTable tabla;
  // End of variables declaration//GEN-END:variables
}
