/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructura;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Array2 extends javax.swing.JFrame {

  
  private int tam;
  private int [] array;
  
  /**
   * Creates new form Array2
   */
  public Array2() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    tamano = new javax.swing.JButton();
    llenar = new javax.swing.JButton();
    mostrar = new javax.swing.JButton();
    sumar = new javax.swing.JButton();
    mayor = new javax.swing.JButton();
    repetir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(219, 207, 231));

    tamano.setText("Tamaño");
    tamano.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tamanoActionPerformed(evt);
      }
    });

    llenar.setText("Llenar array");
    llenar.setEnabled(false);
    llenar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        llenarActionPerformed(evt);
      }
    });

    mostrar.setText("Mostrar ");
    mostrar.setEnabled(false);
    mostrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mostrarActionPerformed(evt);
      }
    });

    sumar.setText("sumar");
    sumar.setEnabled(false);
    sumar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sumarActionPerformed(evt);
      }
    });

    mayor.setText("mayor numero");
    mayor.setEnabled(false);
    mayor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        mayorActionPerformed(evt);
      }
    });

    repetir.setText("valores repetidos");
    repetir.setEnabled(false);
    repetir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        repetirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(39, 39, 39)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(113, 113, 113)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(llenar)
          .addComponent(mayor))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(mostrar)
          .addComponent(repetir))
        .addGap(73, 73, 73))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(167, 167, 167)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(tamano, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
          .addComponent(llenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(71, 71, 71)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(sumar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(mayor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(repetir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(93, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void llenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llenarActionPerformed
    for(int i =0; i<array.length; i++){
      array[i] = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese numero en la posicion "+(i+1)));
    }
    mostrar.setEnabled(true);
    sumar.setEnabled(true);
    repetir.setEnabled(true);
    mayor.setEnabled(true);
  }//GEN-LAST:event_llenarActionPerformed

  private void tamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanoActionPerformed
    int tam = Integer.parseInt(JOptionPane.showInputDialog(null, "ingrese el tamaño del array"));
    array = new int[tam];
    llenar.setEnabled(true);
  }//GEN-LAST:event_tamanoActionPerformed

  private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
   
    String mensaje = "<html>";
    for(int a : array){
      mensaje+=Integer.toString(a)+"<p>";
    }
    mensaje+="<html>";
    JOptionPane.showMessageDialog(rootPane, mensaje);   
    
  }//GEN-LAST:event_mostrarActionPerformed

  private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
    
    int sumaTotal =0;
    for(int i =0; i<array.length; i++){
      sumaTotal+= array[i];
    }
    JOptionPane.showMessageDialog(rootPane, sumaTotal);
    
  }//GEN-LAST:event_sumarActionPerformed

  private void mayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorActionPerformed
    int may=0, pos=0;
    for(int a =0; a<array.length; a++){
      if(array[a]>may){
        may = array[a];
        pos = a;
      }
    }
    JOptionPane.showMessageDialog(rootPane, "el numero mayor es: "+may+" y se encuentra en la posicion "+pos);

  }//GEN-LAST:event_mayorActionPerformed

  private void repetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repetirActionPerformed
   
    String valoresRepet = "<html>";
    int aux=0;
    String pos= "";
    
    for(int i=0; i<array.length; i++){
      for(int j=i; j<array.length; j++){
        if(j!=i){
          if(array[i] == array[j]){
            if(array[i] != aux){
            valoresRepet += array[i]+" en la posicion ";
            pos += i + " "+j;
            valoresRepet+= pos +"<p>";
            }
            aux = array[i];
            pos = "";
          }          
        }
      }
    }
    valoresRepet+="<html>";
        JOptionPane.showMessageDialog(rootPane, valoresRepet);
    
  }//GEN-LAST:event_repetirActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Array2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Array2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Array2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Array2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Array2().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JButton llenar;
  private javax.swing.JButton mayor;
  private javax.swing.JButton mostrar;
  private javax.swing.JButton repetir;
  private javax.swing.JButton sumar;
  private javax.swing.JButton tamano;
  // End of variables declaration//GEN-END:variables
}
